export const ingredients = [
  "maida flour",
  "yogurt",
  "oil",
  "sugar",
  "gram flour",
  "ghee",
  "carrots",
  "milk",
  "cashews",
  "raisins",
  "flour",
  "kewra",
  "clarified butter",
  "almonds",
  "pistachio",
  "saffron",
  "green cardamom",
  "milk powder",
  "plain flour",
  "baking powder",
  "water",
  "rose water",
  "sugar syrup",
  "lentil flour",
  "corn flour",
  "baking soda",
  "vinegar",
  "curd",
  "turmeric",
  "cardamom",
  "cashews and raisins",
  "jaggery syrup",
  "cottage cheese",
  "rice",
  "dried fruits",
  "nuts",
  "firm white pumpkin",
  "kitchen lime",
  "alum powder",
  "semolina",
  "khoa",
  "coconut",
  "molu leaf",
  "corn flour",
  "dry fruits",
  "chenna cheese",
  "cream",
  "lemon juice",
  "coconut flakes",
  "condensed milk",
  "pistachio",
  "reduced milk",
  "elachi",
  "khus-khus seeds",
  "besan",
  "jaggery",
  "cardamom powder",
  "peanuts",
  "dharwadi buffalo milk",
  "loaf bread",
  "salt",
  "semolina",
  "black lentils",
  "mung bean",
  "skimmed milk powder",
  "turmeric",
  "chickpeas",
  "powdered sugar",
  "apricots",
  "sugar syrup",
  "vermicelli pudding",
  "banana",
  "wheat flour",
  "chana dal",
  "hot water",
  "grated coconut",
  "cucumber",
  "rava",
  "dry fruits",
  "semolina",
  "mawa",
  "desiccated coconut",
  "almonds",
  "raisins",
  "cashew nuts",
  "potol",
  "tomato",
  "chillies",
  "ginger",
  "garlic",
  "boiled pork",
  "onions",
  "axone",
  "water",
  "cauliflower",
  "potato",
  "fenugreek leaves",
  "shimla mirch",
  "amchur powder",
  "chole",
  "rava",
  "yogurt",
  "plain flour",
  "baking soda",
  "ladies finger",
  "kasuri methi",
  "chili powder",
  "chicken thighs",
  "basmati rice",
  "star anise",
  "sweet",
  "green chillies",
  "greek yogurt",
  "cream",
  "cashew nuts",
  "butter",
  "chickpeas",
  "tomato paste",
  "red onion",
  "avocado oil",
  "whole wheat flour",
  "olive oil",
  "dahi",
  "sesame seeds",
  "naan bread",
  "tomato sauce",
  "skinless chicken breasts",
  "heavy cream",
  "whole wheat bread",
  "rice flour",
  "whole egg",
  "bay leaf",
  "cinnamon stick",
  "moong dal",
  "masoor dal",
  "wheat flour",
  "almond",
  "garlic",
  "green chilli",
  "red kidney beans",
  "pigeon peas",
  "baby potatoes",
  "beaten rice flakes",
  "curry leaves",
  "lemon juice",
  "arhar dal",
  "white urad dal",
  "dough",
  "fennel seeds",
  "cottage cheese",
  "bell peppers",
  "gravy",
  "paneer",
  "whipping cream",
  "tandoori masala",
  "bell pepper",
  "kala chana",
  "mashed potato",
  "boondi",
  "sev",
  "pomegranate",
  "musk melon seeds",
  "poppy seeds",
  "edible gum",
  "arbi ke patte",
  "gur",
  "imli",
  "fennel",
  "tea bags",
  "mustard oil",
  "red kidney beans",
  "ginger",
  "cinnamon",
  "potatoes",
  "green peas",
  "green chili",
  "rose syrup",
  "falooda sev",
  "mixed nuts",
  "bitter gourd",
  "gram flour",
  "nigella seeds",
  "chana dal",
  "urad dal",
  "spinach",
  "greens",
  "fenugreek seeds",
  "amaranth leaves",
  "red chili",
  "beef",
  "drumstick",
  "tamarind paste",
  "sambar powder",
  "cabbage",
  "tamarind",
  "cucumber",
  "gooseberry",
  "raw rice",
  "pearl onions",
  "drumsticks",
  "thick poha",
  "butter",
  "sugar",
  "brown rice flour",
  "split pigeon peas",
  "french beans",
  "thin rice flakes",
  "black sesame seeds",
  "parboiled rice",
  "steamer",
  "whole red beans",
  "masala",
  "hot water",
  "meat curry powder",
  "chicken chunks",
  "cinnamon",
  "kala masala",
  "sorghum flour",
  "sweet potato",
  "surti papdi",
  "baby potatoes",
  "valor papdi",
  "gobi",
  "khus khus",
  "wine vinegar",
  "banana flower",
  "lobster",
  "fresh green chilli",
  "fish roe",
  "pumpkin flowers",
  "tea leaves",
  "white sesame seeds",
  "soaked rice",
  "basmati rice",
  "rose water",
  "clarified butter",
  "black pepper",
  "ginger powder",
  "egg yolks",
  "arrowroot powder",
  "dry dates",
  "dried rose petals",
  "pistachio",
  "badam",
  "brown rice",
  "fennel seeds",
  "grated coconut",
  "black pepper",
  "ginger powder",
  "baking powder",
  "fish fillet",
  "mint",
  "fermented bamboo shoot",
  "lemon",
  "mustard seed",
  "green",
  "coriander",
  "biryani masala",
  "yellow moong daal",
  "whole red",
  "forbidden black rice",
  "slivered almonds",
  "garlic powder",
  "cooked rice",
  "dry chilli",
  "dry coconut",
  "cardamom pods",
  "lobster",
  "fresh green chilli",
  "turmeric",
  "sugar",
  "red pepper",
  "red onion",
  "butter",
  "watercress",
  "ridge gourd",
  "banana",
  "brinjal",
  "glutinous rice",
  "gur",
  "coconut milk",
  "egg yolks",
  "clarified butter",
  "all purpose flour",
  "cottage cheese",
  "dry fruits",
  "arrowroot powder",
  "all purpose flour",
  "brown rice",
  "fennel seeds",
  "grated coconut",
  "black pepper",
  "ginger powder",
  "bottle gourd",
  "coconut oil",
  "garam masala",
  "ginger",
  "green chillies",
];
